### PR TITLE
Fixes issues with index.jsx and Routes.jsx

### PR DESCRIPTION
**Pull request by owieboy**

### CODE REVIEW

**Comment by zxcpoiu** [comment]
Ha, after fixed it myself, I found I did everything the same like yours.
Anyway, I can confirm this PR will work.

**Comment by ssteinerx** [comment]
@owieboy , @zxcpoiu  -- Could you please file this pull request against my repo at https://github.com/ssteinerx/sb-admin-react -- I'm actively working on it and will merge reasonable pull requests right away if they don't break things.

**Comment by zxcpoiu** [comment]
wow, glad to see someone in actively development. thanks for mention it and your work :+1: 

This PR is not being merged yet but I guess it has been fixed and included in code. both on this repo and yours.

**Comment by ssteinerx** [comment]
@zxcpoiu Could you please close this if the work has been done?

**Comment by zxcpoiu** [comment]
oh, I'm not the author of this PR nor collaborators of this project.
I don't have permissions to close.

cc @owieboy

**Comment by ssteinerx** [comment]
Crap.  cc @owieboy @zxcpoiu

**Pull request merged**
